export const datas = [
  {
    id: 1,
    title: "Ivans xtc.",
    description: "Displ oblique fx shaft of l tibia, 7thJ",
    img: "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-121903546.jpg",
    count: "3346112438",
    author: "Mr",
  },
  {
    id: 2,
    title: "Aftermath: Population Zero",
    description: "Nondisp seg fx shaft of unsp fibula, 7thF",
    img: "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-121903546.jpg",
    count: "2008070255",
    author: "Dr",
  },
  {
    id: 3,
    title: "Rutles 2: Can't Buy Me Lunch, The",
    description: "Ped on rolr-skt inj pick-up truck, pk-up/van, unsp, sequela",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "4200724200",
    author: "Mr",
  },
  {
    id: 4,
    title: "Inadequate People (Neadekvatnye lyudi)",
    description: "Pnctr w fb of right lesser toe(s) w damage to nail, sequela",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "2987674295",
    author: "Mr",
  },
  {
    id: 5,
    title: "Camp Nowhere",
    description: "Suprvsn of preg w poor reprodctv or obstet hx, second tri",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "4341595946",
    author: "Mr",
  },
  {
    id: 6,
    title: "Planet of the Vampires (Terrore nello spazio)",
    description: "Colles' fracture of right radius, init for opn fx type I/2",
    img: "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-121903546.jpg",
    count: "2863502565",
    author: "Mrs",
  },
  {
    id: 7,
    title:
      "Spiders, Part 2: The Diamond Ship, The (Die Spinnen, 2. Teil - Das Brillantenschiff)",
    description: "Milt op w dest arcrft due to onboard fire, civilian, init",
    img: "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-121903546.jpg",
    count: "9848011382",
    author: "Mrs",
  },
  {
    id: 8,
    title: "Waterloo",
    description: "Other albinism with hematologic abnormality",
    img: "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_1280.jpg",
    count: "7318018183",
    author: "Mr",
  },
  {
    id: 9,
    title: "The Sex and Violence Family Hour",
    description: "Abnormal hard tissue formation in pulp",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "2161564439",
    author: "Mr",
  },
  {
    id: 10,
    title: "Way of the Gun, The",
    description: "Disp fx of medial phalanx of l little fngr, init for opn fx",
    img: "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_1280.jpg",
    count: "5389449037",
    author: "Mr",
  },
  {
    id: 11,
    title: "Where's Marlowe?",
    description: "Disp fx of 2nd metatarsal bone, l ft, 7thD",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "2972844351",
    author: "Mrs",
  },
  {
    id: 12,
    title: "Comic Book Confidential",
    description: "Oth injury of extn musc/fasc/tend at forearm level",
    img: "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_1280.jpg",
    count: "7856656069",
    author: "Ms",
  },
  {
    id: 13,
    title: "Card Subject To Change",
    description: "Pathological fracture, unspecified site, sequela",
    img: "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-121903546.jpg",
    count: "4285390493",
    author: "Ms",
  },
  {
    id: 14,
    title: "Alexandria... Why? (Iskanderija... lih?)",
    description: "Other fracture of lower end of unspecified tibia",
    img: "http://dummyimage.com/x.png/dddddd/000000",
    count: "4189822469",
    author: "Mrs",
  },
  {
    id: 15,
    title: "Dilettante, La",
    description: "Toxic effect of rattlesnake venom, undetermined, sequela",
    img: "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_1280.jpg",
    count: "8201922956",
    author: "Honorable",
  },
  {
    id: 16,
    title: "Visitor Q (Bizita Q)",
    description: "Puncture wound without foreign body, right foot",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "6243622894",
    author: "Dr",
  },
  {
    id: 17,
    title: "Porto of My Childhood (Porto da Minha Infância)",
    description: "Drug-induced chronic gout, right hip",
    img: "https://media.istockphoto.com/id/1358013032/photo/web-development-concept.jpg?s=612x612&w=0&k=20&c=d0F_7Rs2bysfEL9zr9JVN1TLzVOlEycNkz-vd19OANA=",
    count: "3865093191",
    author: "Mr",
  },
  {
    id: 18,
    title: "Proof of Life",
    description: "Occup of bus injured in clsn w statnry object nontraf, subs",
    img: "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-121903546.jpg",
    count: "2587508312",
    author: "Dr",
  },
  {
    id: 19,
    title: "Human Tornado, The",
    description: "Soemmering's ring, unspecified eye",
    img: "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_1280.jpg",
    count: "0113551320",
    author: "Mrs",
  },
  {
    id: 20,
    title: "Advanced Style",
    description: "Disp fx of prox phalanx of r little finger, init for opn fx",
    img: "https://media.istockphoto.com/id/1358013032/photo/web-development-concept.jpg?s=612x612&w=0&k=20&c=d0F_7Rs2bysfEL9zr9JVN1TLzVOlEycNkz-vd19OANA=",
    count: "4907389531",
    author: "Honorable",
  },
  {
    id: 21,
    title: "Chosen One, The",
    description: "Other subluxation of unspecified knee, subsequent encounter",
    img: "https://thumbs.dreamstime.com/b/web-development-coding-programming-internet-technology-business-concept-web-development-coding-programming-internet-technology-121903546.jpg",
    count: "2448563640",
    author: "Ms",
  },
  {
    id: 22,
    title: "Madame Butterfly",
    description: "Unstable burst fracture of fifth lumbar vertebra, sequela",
    img: "https://media.istockphoto.com/id/1358013032/photo/web-development-concept.jpg?s=612x612&w=0&k=20&c=d0F_7Rs2bysfEL9zr9JVN1TLzVOlEycNkz-vd19OANA=",
    count: "5570027637",
    author: "Mr",
  },
  {
    id: 23,
    title: "Stranger on the Prowl (Imbarco a mezzanotte)",
    description: "Oth fracture of oth metacarpal bone, init for clos fx",
    img: "http://dummyimage.com/x.png/dddddd/000000",
    count: "8205497540",
    author: "Dr",
  },
  {
    id: 24,
    title: "Questioning Darwin",
    description: "Poisn by slctv serotonin reuptake inhibtr, assault, sequela",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "1137657332",
    author: "Rev",
  },
  {
    id: 25,
    title: "Mr. Freedom",
    description: "Bitten by horse, subsequent encounter",
    img: "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_1280.jpg",
    count: "9531435375",
    author: "Mr",
  },
  {
    id: 26,
    title:
      "Easy Riders, Raging Bulls: How the Sex, Drugs and Rock 'N' Roll Generation Saved Hollywood",
    description: "Encounter for adequacy testing for peritoneal dialysis",
    img: "https://media.istockphoto.com/id/1371339413/photo/co-working-team-meeting-concept-businessman-using-smart-phone-and-digital-tablet-and-laptop.webp?b=1&s=170667a&w=0&k=20&c=GnW36mPEYr3TRpPZNLtT75u8v2HOczvRxGckWUN3hVg=",
    count: "1581661150",
    author: "Rev",
  },
];
